baseURL = 'https://campuspulse.app/'
languageCode = 'en-us'
title = 'CampusPulse - Your hub for quick campus resources'

[module]
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/font-awesome'
