baseURL = 'https://campuspulse.app/'
languageCode = 'en-us'
title = 'CampusPulse - The student-built mobile resources hub for RIT'

[module]
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/font-awesome'
